---
title: "AKSEN - DÖNEM ÖDEVİ"
author: "Ünal Giray Ergün - Bünyamin Akın"
date: "`r Sys.Date()`"
output: word_document
---

Veri yükleme
```{r}
veri <- read.csv("AKSEN.IS.csv")
```

Kapanis fiyatinin tanimlanmasi
```{r}
kapanisfiyat <- veri$Close
```

Ortalama hesaplama
```{r}
mean(kapanisfiyat)
```

Medyan
```{r}
median(kapanisfiyat)

```

Mod
```{r}
modfiyat <- table(kapanisfiyat)
names(modfiyat)[which(modfiyat == max(modfiyat))]

```

Çeyriklik ve yüzdeliklerin bulunmasi

```{r}
quantile(kapanisfiyat)
quantile(kapanisfiyat, probs= c(10,25,75,90)/100)

```

Varyans - Standart Sapma - Standart Hata
```{r}
var(kapanisfiyat)
sd(kapanisfiyat)
std_hata <- sd(kapanisfiyat)/sqrt(length(kapanisfiyat))
std_hata
```
Çarpıklık Katsayısı(Skewness) - Basıklık Katsayısı(Kurtosis)
```{r}
library(moments)
#Çarpıklık Katsayısı
skewness(kapanisfiyat)

#Basıklık Katsayısı
kurtosis(kapanisfiyat)
```
Bowley'in Asimetri Ölçüsü - Pearson'ın asimetri ölçüsü
```{r}
#Bowley'in Asimetri Ölçüsü - Pearson'ın asimetri ölçüsü
#Bowley
q1_fiyat <- 39
q2_fiyat <- 42.910
q3_fiyat <- 48.035
bow_fiyat <- (q3_fiyat+q1_fiyat-(2*q2_fiyat))/(q3_fiyat-q1_fiyat)
bow_fiyat
#Pearson
pear_fiyat <- 3*(mean(kapanisfiyat)-median(kapanisfiyat))/sd(kapanisfiyat)
pear_fiyat

```

Histogram Grafiği
```{r}
hist(kapanisfiyat, main="AKSEN Son 60 Günün Kapaniş Fiyatlarının Histogramı", xlab="Kapanis fiyati", ylab="Frekans")
```

Birikimli Sıklık Grafiği
```{r}
f <- c(4,6,4,8,10,10,12,6)
plot(cumsum(f),type="o",main="Birikimli Sıklık Grafiği",xlab="Kapanis fiyati",ylab="Birikimli Sıklık")
```

Trend Grafiği
```{r}
plot(ts(kapanisfiyat), type="o",main="AKSEN Son 60 Günün Kapaniş Fiyatlarının Trend Grafiği", xlab="Gün",ylab="Kapanis Fiyati")
```

Boxplot Grafiği
```{r}
boxplot(kapanisfiyat, col="pink")
```
